Pandas/ohana-api-master/config/routes.rb
require 'api_constraints'
require 'subdomain_constraints'

Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'user/registrations' }
  devise_for(
    :admins, path: ENV['ADMIN_PATH'] || '/', controllers: { registrations: 'admin/registrations' }
  )

  constraints(SubdomainConstraints.new(subdomain: ENV['ADMIN_SUBDOMAIN'])) do
    namespace :admin, path: ENV['ADMIN_PATH'] do
      root to: 'dashboard#index', as: :dashboard

      resources :locations, except: :show do
        resources :services, except: %i[show index] do
          resources :contacts, except: %i[show index], controller: 'service_contacts'
        end
        resources :contacts, except: %i[show index]
      end

      resources :organizations, except: :show do
        resources :contacts, except: %i[show index], controller: 'organization_contacts'
      end
      resources :programs, except: :show
      resources :services, only: :index

      namespace :csv, defaults: { format: 'csv' } do
        get 'addresses'
        get 'contacts'
        get 'holiday_schedules'
        get 'locations'
        get 'mail_addresses'
        get 'organizations'
        get 'phones'
        get 'programs'
        get 'regular_schedules'
        get 'services'
      end

      get 'locations/:location_id/services/:id', to: 'services#edit'
      get 'locations/:location_id/services/:service_id/contacts/:id', to: 'service_contacts#edit'
      get 'locations/:location_id/contacts/:id', to: 'contacts#edit'
      get 'locations/:id', to: 'locations#edit'
      get 'organizations/:id', to: 'organizations#edit'
      get 'organizations/:organization_id/contacts/:id', to: 'organization_contacts#edit'
      get 'programs/:id', to: 'programs#edit'
    end
  end

  resources :api_applications, except: :show
  get 'api_applications/:id' => 'api_applications#edit'

  constraints(SubdomainConstraints.new(subdomain: ENV['API_SUBDOMAIN'])) do
    namespace :api, path: ENV['API_PATH'], defaults: { format: 'json' } do
      scope module: :v1, constraints: ApiConstraints.new(version: 1) do
        get '/' => 'root#index'
        get '.well-known/status' => 'status#check_status'

        resources :organizations do
          resources :locations, only: :create
        end
        get 'organizations/:organization_id/locations',
            to: 'organizations#locations', as: :org_locations

        resources :locations do
          resources :address, except: %i[index show]
          resources :mail_address, except: %i[index show]
          resources :contacts, except: [:show] do
            resources :phones,
                      except: %i[show index],
                      path: '/phones', controller: 'contact_phones'
          end
          resources :phones, except: [:show], path: '/phones', controller: 'location_phones'
          resources :services
        end

        resources :search, only: :index

        resources :categories, only: :index

        put 'services/:service_id/categories',
            to: 'services#update_categories', as: :service_categories
        get 'categories/:taxonomy_id/children', to: 'categories#children', as: :category_children
        get 'locations/:location_id/nearby', to: 'search#nearby', as: :location_nearby

        match '*unmatched_route' => 'errors#raise_not_found!',
              via: %i[get delete patch post put]

        match '*unmatched_route' => 'cors#render_204', via: [:options]
      end
    end
  end

  root to: 'home#index'
end

Pandas/ohana-api-master/app/models/program.rb
class Program < ApplicationRecord
  belongs_to :organization, optional: false
  has_many :services, dependent: :destroy

  validates :name,
            presence: { message: I18n.t('errors.messages.blank_for_program') }

  auto_strip_attributes :alternate_name, :name

  def self.with_orgs(ids)
    joins(:organization).where(organization_id: ids).distinct
  end
end

Pandas/ohana-api-master/app/controllers/admin/programs_controller.rb
class Admin
  class ProgramsController < ApplicationController
    before_action :authenticate_admin!
    layout 'admin'

    def index
      @programs = Kaminari.paginate_array(policy_scope(Program)).
                  page(params[:page]).per(params[:per_page])
    end

    def edit
      @program = Program.find(params[:id])

      authorize @program
    end

    def update
      @program = Program.find(params[:id])

      authorize @program

      if @program.update(program_params)
        redirect_to [:admin, @program],
                    notice: 'Program was successfully updated.'
      else
        render :edit
      end
    end

    def new
      @program = Program.new
      authorize @program
    end

    def create
      @program = Program.new(program_params)
      org = @program.organization

      authorize @program if org.present?

      if @program.save
        redirect_to admin_programs_url,
                    notice: 'Program was successfully created.'
      else
        render :new
      end
    end

    def destroy
      program = Program.find(params[:id])
      authorize program
      program.destroy
      redirect_to admin_programs_url
    end

    private

    def program_params
      params.require(:program).permit(:alternate_name, :name, :organization_id)
    end
  end
end

Pandas/ohana-api-master/app/views/admin/programs/_confirm_delete_program.html.haml
.modal-dialog
  .modal-content
    .modal-header
      = button_tag(type: 'button', class: 'close', data: { dismiss: 'modal' }) do
        %span{ 'aria-hidden' => 'true' }
          &times;
        %span.sr-only
          Close
      %h4.modal-title#my-modal-label
        Are you ABSOLUTELY sure?
    .modal-body
      %p
        This action CANNOT be undone. This will delete
        %strong
          = program_name
        and all of its associated services permanently.
    .modal-footer
      %button.btn.btn-default{ 'data-dismiss' => 'modal' } Close
      = link_to t('admin.buttons.confirm_delete_program'), { action: :destroy, id: program_id }, method: :delete, class: 'btn btn-danger'

Pandas/ohana-api-master/app/views/admin/programs/_form.html.haml
= render 'admin/programs/forms/fields', f: f, program: program
= render 'admin/programs/forms/danger', program: program
= render 'admin/programs/forms/editing', f: f, program: program

Pandas/ohana-api-master/app/views/admin/programs/edit.html.haml
.content-box
  %h2 #{@program.organization.try(:name)} / #{@program.name}
= form_for [:admin, @program], html: { class: 'edit-entry' } do |f|
  = render 'admin/programs/form', f: f, program: @program

Pandas/ohana-api-master/app/views/admin/programs/index.html.haml
%p
  Below you should see a list of programs that you are allowed to administer.
  If there are any entries missing,
  please #{mail_to SETTINGS[:admin_support_email], 'let us know'}.
%p
  To start updating, click on one of the links, which will take you to the details page
  for the program.

- if current_admin.super_admin?
  %p
    As a super admin, you have access to all programs in the database. Please make updates responsibly.

%p
  - @programs.each do |program|
    %ul
      = link_to program.second, edit_admin_program_path(program.first)
  = paginate @programs

  - if Pundit.policy_scope!(current_admin, Organization).present?
    = link_to t('admin.buttons.add_program'), new_admin_program_path, class: 'btn btn-primary'

Pandas/ohana-api-master/app/views/admin/programs/new.html.haml
.content-box
  %h1 Create a new program

= form_for [:admin, @program], url: admin_programs_path, html: { method: :post, class: 'edit-entry' } do |f|
  = render 'admin/programs/forms/new_program_form', f: f, program: @program