Pandas/ohana-api-master/config/routes.rb
require 'api_constraints'
require 'subdomain_constraints'

Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'user/registrations' }
  devise_for(
    :admins, path: ENV['ADMIN_PATH'] || '/', controllers: { registrations: 'admin/registrations' }
  )

  constraints(SubdomainConstraints.new(subdomain: ENV['ADMIN_SUBDOMAIN'])) do
    namespace :admin, path: ENV['ADMIN_PATH'] do
      root to: 'dashboard#index', as: :dashboard

      resources :locations, except: :show do
        resources :services, except: %i[show index] do
          resources :contacts, except: %i[show index], controller: 'service_contacts'
        end
        resources :contacts, except: %i[show index]
      end

      resources :organizations, except: :show do
        resources :contacts, except: %i[show index], controller: 'organization_contacts'
      end
      resources :programs, except: :show
      resources :services, only: :index

      namespace :csv, defaults: { format: 'csv' } do
        get 'addresses'
        get 'contacts'
        get 'holiday_schedules'
        get 'locations'
        get 'mail_addresses'
        get 'organizations'
        get 'phones'
        get 'programs'
        get 'regular_schedules'
        get 'services'
      end

      get 'locations/:location_id/services/:id', to: 'services#edit'
      get 'locations/:location_id/services/:service_id/contacts/:id', to: 'service_contacts#edit'
      get 'locations/:location_id/contacts/:id', to: 'contacts#edit'
      get 'locations/:id', to: 'locations#edit'
      get 'organizations/:id', to: 'organizations#edit'
      get 'organizations/:organization_id/contacts/:id', to: 'organization_contacts#edit'
      get 'programs/:id', to: 'programs#edit'
    end
  end

  resources :api_applications, except: :show
  get 'api_applications/:id' => 'api_applications#edit'

  constraints(SubdomainConstraints.new(subdomain: ENV['API_SUBDOMAIN'])) do
    namespace :api, path: ENV['API_PATH'], defaults: { format: 'json' } do
      scope module: :v1, constraints: ApiConstraints.new(version: 1) do
        get '/' => 'root#index'
        get '.well-known/status' => 'status#check_status'

        resources :organizations do
          resources :locations, only: :create
        end
        get 'organizations/:organization_id/locations',
            to: 'organizations#locations', as: :org_locations

        resources :locations do
          resources :address, except: %i[index show]
          resources :mail_address, except: %i[index show]
          resources :contacts, except: [:show] do
            resources :phones,
                      except: %i[show index],
                      path: '/phones', controller: 'contact_phones'
          end
          resources :phones, except: [:show], path: '/phones', controller: 'location_phones'
          resources :services
        end

        resources :search, only: :index

        resources :categories, only: :index

        put 'services/:service_id/categories',
            to: 'services#update_categories', as: :service_categories
        get 'categories/:taxonomy_id/children', to: 'categories#children', as: :category_children
        get 'locations/:location_id/nearby', to: 'search#nearby', as: :location_nearby

        match '*unmatched_route' => 'errors#raise_not_found!',
              via: %i[get delete patch post put]

        match '*unmatched_route' => 'cors#render_204', via: [:options]
      end
    end
  end

  root to: 'home#index'
end

Pandas/ohana-api-master/app/models/service.rb
class Service < ApplicationRecord
  belongs_to :location, touch: true, optional: false
  belongs_to :program, optional: true

  has_and_belongs_to_many :categories,
                          after_add: :touch_location,
                          after_remove: :touch_location

  has_many :regular_schedules, dependent: :destroy, inverse_of: :service
  accepts_nested_attributes_for :regular_schedules,
                                allow_destroy: true, reject_if: :all_blank

  has_many :holiday_schedules, dependent: :destroy, inverse_of: :service
  accepts_nested_attributes_for :holiday_schedules,
                                allow_destroy: true, reject_if: :all_blank

  has_many :contacts, dependent: :destroy, inverse_of: :service

  has_many :phones, dependent: :destroy, inverse_of: :service
  accepts_nested_attributes_for :phones,
                                allow_destroy: true, reject_if: :all_blank

  validates :accepted_payments, :languages, :required_documents, pg_array: true

  validates :email, email: true, allow_blank: true

  validates :name, :description, :status,
            presence: { message: I18n.t('errors.messages.blank_for_service') }

  validates :service_areas, array: { service_area: true }

  validates :website, url: true, allow_blank: true

  auto_strip_attributes :alternate_name, :audience, :description, :eligibility,
                        :email, :fees, :application_process, :interpretation_services,
                        :name, :wait_time, :status, :website

  auto_strip_attributes :funding_sources, :keywords, :service_areas,
                        reject_blank: true, nullify: true, nullify_array: false

  serialize :funding_sources, Array
  serialize :keywords, Array
  serialize :service_areas, Array

  extend Enumerize
  enumerize :status, in: %i[active defunct inactive]

  def self.with_locations(ids)
    joins(:location).where(location_id: ids).distinct
  end

  after_validation :remove_duplicates
  after_save :update_location_status, if: :saved_change_to_status?

  private

  # rubocop:disable Rails/SkipsModelValidations
  def update_location_status
    return if location.active == location_services_active?

    location.update_columns(active: location_services_active?)
  end
  # rubocop:enable Rails/SkipsModelValidations

  def location_services_active?
    location.services.pluck(:status).include?('active')
  end

  # rubocop:disable Rails/SkipsModelValidations
  def touch_location(_category)
    location.update_column(:updated_at, Time.zone.now) if persisted?
  end
  # rubocop:enable Rails/SkipsModelValidations

  def remove_duplicates
    [service_areas, keywords, funding_sources].each(&:uniq!)
  end
end

Pandas/ohana-api-master/app/controllers/admin/services_controller.rb
class Admin
  class ServicesController < ApplicationController
    include Taggable

    before_action :authenticate_admin!
    layout 'admin'

    def index
      @services = Kaminari.paginate_array(policy_scope(Service)).
                  page(params[:page]).per(params[:per_page])
    end

    def edit
      assign_location_service_and_taxonomy_ids

      authorize @location
    end

    def update
      assign_location_service_and_taxonomy_ids
      preprocess_service_params
      authorize @location
      preprocess_service

      if @service.update(service_params.except(:locations))
        redirect_to [:admin, @location, @service],
                    notice: 'Service was successfully updated.'
      else
        render :edit
      end
    end

    def new
      @location = Location.find(params[:location_id])
      taxonomy_ids = []

      authorize @location

      @service = Service.new
      @nested_categories = NestedCategories.new(taxonomy_ids: taxonomy_ids, view: view_context).call
    end

    def create
      prepare_and_authorize_service_creation

      if @service.save
        redirect_to admin_location_url(@location),
                    notice: "Service '#{@service.name}' was successfully created."
      else
        render :new
      end
    end

    def destroy
      service = Service.find(params[:id])
      authorize service.location
      service.destroy
      redirect_to admin_locations_url
    end

    private

    def prepare_and_authorize_service_creation
      preprocess_service_params

      @location = Location.find(params[:location_id])
      @service = @location.services.new(service_params.except(:locations))

      authorize @location
      preprocess_service
    end

    def preprocess_service_params
      shift_and_split_params(params[:service], :keywords)
    end

    def preprocess_service
      add_program_to_service_if_authorized
      add_service_to_location_if_authorized
    end

    def add_program_to_service_if_authorized
      prog_id = service_params[:program_id]
      @service.program = nil and return if prog_id.blank?

      if program_ids_for(@service).select { |id| id == prog_id.to_i }.present?
        @service.program_id = prog_id
      end
    end

    def program_ids_for(service)
      service.location.organization.programs.pluck(:id)
    end

    def add_service_to_location_if_authorized
      return if location_ids.blank?

      location_ids.each do |id|
        Location.find(id.to_i).services.create!(service_params.except(:locations))
      end
    end

    def location_ids
      locations = service_params[:locations]
      return if locations.blank?

      locations.select { |id| location_ids_for(@service).include?(id.to_i) }
    end

    def location_ids_for(service)
      @location_ids_for ||= service.location.organization.locations.pluck(:id)
    end

    def assign_location_service_and_taxonomy_ids
      @service = Service.find(params[:id])
      @location = Location.find(params[:location_id])
      taxonomy_ids = @service.categories.pluck(:taxonomy_id)
      @nested_categories = NestedCategories.new(taxonomy_ids: taxonomy_ids, view: view_context).call
    end

    # rubocop:disable Metrics/MethodLength
    def service_params
      params.require(:service).permit(
        { accepted_payments: [] }, :alternate_name, :audience, :description, :eligibility, :email,
        :fees, { funding_sources: [] }, :application_process, :interpretation_services,
        { keywords: [] }, { languages: [] }, :name, { required_documents: [] },
        { service_areas: [] }, :status, :website, :wait_time, { category_ids: [] },
        :program_id, { locations: [] },
        regular_schedules_attributes: %i[weekday opens_at closes_at id _destroy],
        holiday_schedules_attributes: %i[
          closed start_date end_date opens_at closes_at id _destroy
        ],
        phones_attributes: %i[
          country_prefix department extension number number_type vanity_number id _destroy
        ]
      )
    end
    # rubocop:enable Metrics/MethodLength
  end
end

Pandas/ohana-api-master/app/controllers/api/v1/services_controller.rb
module Api
  module V1
    class ServicesController < ApplicationController
      include TokenValidator
      include CustomErrors
      include CategoryIdCollector

      before_action :validate_token!, only: %i[update destroy create update_categories]

      def index
        location = Location.includes(
          services: %i[categories contacts phones regular_schedules
                       holiday_schedules]
        ).find(params[:location_id])
        services = location.services
        render json: services, status: :ok
      end

      def update
        service = Service.find(params[:id])
        service.update!(service_params)
        render json: service, status: :ok
      end

      def create
        location = Location.find(params[:location_id])
        service = location.services.create!(service_params)
        render json: service, status: :created
      end

      def destroy
        service = Service.find(params[:id])
        service.destroy
        head :no_content
      end

      def update_categories
        service = Service.find(params[:service_id])
        service.category_ids = cat_ids(service_params[:taxonomy_ids])
        service.save!

        render json: service, status: :ok
      end

      private

      def service_params
        params.permit(
          { accepted_payments: [] }, :alternate_name, :audience, :description,
          :eligibility, :email, :fees, { funding_sources: [] },
          :application_process, :interpretation_services, { keywords: [] },
          { languages: [] }, :name, { required_documents: [] },
          { service_areas: [] }, :status, :website, :wait_time, taxonomy_ids: []
        )
      end
    end
  end
end

Pandas/ohana-api-master/app/views/admin/services/_confirm_delete_service.html.haml
.modal-dialog
  .modal-content
    .modal-header
      = button_tag(type: 'button', class: 'close', data: { dismiss: 'modal' }) do
        %span{ 'aria-hidden' => 'true' }
          &times;
        %span.sr-only
          Close
      %h4.modal-title#my-modal-label
        Are you ABSOLUTELY sure?
    .modal-body
      %p
        This action CANNOT be undone. This will delete
        %strong
          #{service_name || service_id}.
    .modal-footer
      %button.btn.btn-default{ 'data-dismiss' => 'modal' }  Close
      = link_to t('admin.buttons.confirm_delete_service'), { action: :destroy, id: service_id, name: service_name }, method: :delete, class: 'btn btn-danger'

Pandas/ohana-api-master/app/views/admin/services/_form.html.haml
= render 'admin/services/forms/fields', f: f, service: service, nested_categories: nested_categories, location: location
.content-box
  %h2 Contacts
  - if service.contacts.present?
    Click a Contact below to view and update it:
    %p
    - service.contacts.each do |contact|
      = link_to contact.name, edit_admin_location_service_contact_path(location, service, contact)
      %br
  %p
    = link_to t('admin.buttons.add_contact'), new_admin_location_service_contact_path(location, service), class: 'btn btn-primary'

= render 'admin/services/forms/service_locations', location: location, service: service

.danger-zone
  %header
    %strong
      Danger Zone
  %h4
    Delete this service
  %p
    Once you delete a service, there is no going back. Please be certain.
  %p
    = link_to t('admin.buttons.delete_service'), {}, href: '', data: { toggle: 'modal', target: '#modal-window' }, class: 'boxed-action'
.modal.fade#modal-window{ 'aria-hidden' => 'true', 'aria-labelledby' => 'my-modal-label', 'role' => 'dialog', 'tabindex' => '-1' }
  = render 'admin/services/confirm_delete_service', service_id: service.id, service_name: service.name

.save-box.navbar-default
  %p
    Editing
    %strong
      #{service.name} / #{location.name}
  = f.submit t('admin.buttons.save_changes'), class: 'btn btn-success', data: { disable_with: 'Please wait...' }

Pandas/ohana-api-master/app/views/admin/services/edit.html.haml
.content-box
  %h2 #{@service.try(:name)} / #{@location.name}
= form_for [:admin, @location, @service], html: { class: 'edit-entry' } do |f|
  = render 'admin/services/form', f: f, service: @service, location: @location, nested_categories: @nested_categories

Pandas/ohana-api-master/app/views/admin/services/index.html.haml
%p
  Below you should see a list of services (and their corresponding location) that you are allowed to administer.
  If there are any entries missing,
  please #{mail_to SETTINGS[:admin_support_email], 'let us know'}.
%p
  To start updating, click on one of the links, which will take you to the details page
  for the service.

- if current_admin.super_admin?
  %p
    As a super admin, you have access to all services in the database. Please make updates responsibly.

%p
  - @services.each do |service|
    %ul
      - location_name ||= Location.find(service[0]).name
      = link_to "#{service[2]} / #{location_name}", edit_admin_location_service_path(service[0], service[1])
  = paginate @services

Pandas/ohana-api-master/app/views/admin/services/new.html.haml
.content-box
  %h1 Create a new service

= form_for [:admin, @location, @service], html: { method: :post, class: 'edit-entry' } do |f|
  = render 'admin/services/forms/new_service_form', f: f, location: @location, service: @service, nested_categories: @nested_categories